### PR TITLE
export filtering step to standalone script

### PR DESCRIPTION
**Pull request by clami66**
Here the krakenuniq output filtering is done only once in a small script, then the `krakenuniq.output.filtered` output is used wherever possible to avoid redundant filtering steps

Notice how the hardcoded 1000 in `filtered_taxIDs_kmers1000` should be changed at a later stage since the "1000" comes from a configurable parameter

### CODE REVIEW

**Comment by clami66** [comment]
Fixes #88

**Comment by clami66** [comment]
And here is how the DAG looks now:
image

**Review by percyfal — APPROVED** [review]
LGTM! I assume you have verified that the final output is identical?

**Comment by clami66** [comment]
It is for the test output. Should we add a diff check in the github actions?

**Comment by percyfal** [comment]
I guess at some point we should. It's one thing that the workflow runs, another that we actually can reproduce the same results. I think this will take some time to implement though. Anyhow, I'll go ahead and merge and we could keep this in mind for the future.

**Pull request merged**
