### PR TITLE
Add support for multiple adapters

### LINKED ISSUE #76: add nextera adapter removal
I realized that we are by default removing only illumina adapters. Would be good to add a rule that can figure out from the FastQC report whether it is illumina or nextera adapters and if it is nextera then it removes the adapters with:

`cutadapt -a CTGTCTCTTATA --minimum-length 30 -o sample.trimmed.fastq.gz sample.merged.fastq.gz -j 10`

### PR DESCRIPTION
**Pull request by percyfal**
Fixes #76

### CODE REVIEW

**Comment by NikolayOskolkov** [comment]
@percyfal great job! Would it be possible to add an option for the users to choose between Illumina and Nextera (I guess those are the most common)? I remove Nextera adapters with Cutadapt like this:

`cutadapt -a CTGTCTCTTATA --minimum-length 30 -o BC-0302374998.raw__raw_reads.merged.trimmed.fastq.gz BC-0302374998.raw__raw_reads.merged.fastq.gz -j 80`

**Comment by percyfal** [comment]
Could there be a mix of adapters in a project? One way of doing this could be to add boolean configuration options for illumina and nextera, e.g. `illumina_adapter` and `nextera_adapter`, and let the list defined above be a list of whatever adapter sequences the user wants to supply to the workflow. How does that sound?

**Comment by NikolayOskolkov** [comment]
Yes, this sounds good! I would set "illumina_adapter" by default and mention it in the documentation and give the users an option to switch to "nextera_adapter" if they want, or add their own adapter sequences

**Comment by percyfal** [comment]
@LeandroRitter Ok I updated the PR. Now adapters are defined in the `adapters` configuration section, with the following defaults:

```
adapters:
  illumina: true
  nextera: false
  custom: []
```

Custom adapters can be defined in adapters:custom. I was hesitant to organize it this way because it is an inconsistent mix of booleans and a list of strings; what do you think? Please make sure to read the update docs to verify you understand what I mean.

**Review by NikolayOskolkov — APPROVED** [review]

**Pull request merged**
